[package]
name = "wgpu_glyph"
version = "0.3.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A fast text renderer for wgpu, powered by glyph_brush"
license = "MIT"
keywords = ["font", "ttf", "truetype", "wgpu", "text"]
repository = "https://github.com/hecrj/wgpu_glyph"
documentation = "https://docs.rs/wgpu_glyph"
readme = "README.md"

[dependencies]
wgpu = { version = "0.2" }
glyph_brush = "0.5"
log = "0.4"

[dev-dependencies]
env_logger = "0.6"

[patch.crates-io]
gfx-hal = { git = "https://github.com/hecrj/gfx", branch = "web" }
gfx-backend-empty = { git = "https://github.com/hecrj/gfx", branch = "web" }
wgpu = { git = "https://github.com/hecrj/wgpu-rs", branch = "web" }
wgpu-native = { git = "https://github.com/hecrj/wgpu", branch = "web" }
winit = { git = "https://github.com/hecrj/winit", branch = "web" }
